
#ifndef CONFIG_H
#define CONFIG_H

#define ODRIVE_BAUD_RATE 115200
#define MOTOR_CALIBRATION_CURRENT 30
#define MOTOR_INDEX_SEARCH_LOCKIN_SPEED 5
#define MOTOR_DRIVE_CURRENT 30
#define MOTOR_POLE_PAIRS 7
#define MOTOR_TORQUE_CONSTANT (8.27 / 150.0)
#define ENCODER_CPR 8192

#define MOTOR_GAIN_P 300.f
#define MOTOR_GAIN_I 1.f
#define MOTOR_GAIN_D 0.2f

// End stops
#define END_STOP_GPIO_AXIS0 3
#define END_STOP_GPIO_AXIS1 4
#define END_STOP_GPIO_AXIS2 3
#define END_STOP_GPIO_AXIS3 4
#define END_STOP_OFFSET_AXIS0 -0.5f
#define END_STOP_OFFSET_AXIS1 0.5f
#define END_STOP_OFFSET_AXIS2 0.f
#define END_STOP_OFFSET_AXIS3 0.f

#define AXIS0_REDUCTION_RATIO 25.f
#define AXIS0_ZERO_OFFSET degrees(asin(18.f / 51.f))
#define AXIS0_MIN_ANGLE AXIS0_ZERO_OFFSET
#define AXIS0_MAX_ANGLE 90.f

#define AXIS1_REDUCTION_RATIO 16.f
#define AXIS1_ZERO_OFFSET degrees(asin(22.f / 57.f))
#define AXIS1_MIN_ANGLE AXIS1_ZERO_OFFSET
#define AXIS1_MAX_ANGLE 90.f

#define AXIS2_REDUCTION_RATIO 16.f
#define AXIS2_ZERO_OFFSET 0
#define AXIS2_MIN_ANGLE AXIS2_ZERO_OFFSET
#define AXIS2_MAX_ANGLE 90.f

#define AXIS3_REDUCTION_RATIO 16.f
#define AXIS3_ZERO_OFFSET 0
#define AXIS3_MIN_ANGLE AXIS3_ZERO_OFFSET
#define AXIS3_MAX_ANGLE 90.f

//#define ENDSTOP_OFFSET_AXIS0 -0.5
//#define ENDSTOP_OFFSET_AXIS1 0.5
//#define ENDSTOP_OFFSET_AXIS2 0
//#define ENDSTOP_OFFSET_AXIS3 0
//
//#define CALIBRATION_CURRENT 30.f
//#define DRIVE_CURRENT 50.f
//#define MOTOR_TORQUE_CONSTANT (8.27f / 150.f)
//
//#define TR_HOMING_ACCEL 2.f
//#define TR_HOMING_VEL 2.f
//#define TR_HOMING_DECEL 2.f
//#define TR_HOMING_POS_OVER_ENDSTOP 0.5f    // Rotations
//#define HOMING_SPEED 0.05

#endif // CONFIG_H
