/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_FLAME_FLAME_PB_H_INCLUDED
#define PB_FLAME_FLAME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _FLAME_DiscoveryPacket { 
    char dummy_field;
} FLAME_DiscoveryPacket;

typedef struct _FLAME_ControlPacket { 
    float desiredAxis1;
    float desiredAxis2;
    float desiredAxis3;
    float desiredAxis4;
    bool odrive0Axis0Error;
    bool odrive0Axis1Error;
    bool odrive0Error;
    bool odrv0ClearErrors;
    bool odrive1Axis0Error;
    bool odrive1Axis1Error;
    bool odrive1Error;
    bool odrv1ClearErrors;
    bool clearSafetyMode;
} FLAME_ControlPacket;

typedef struct _FLAME_DiscoveryResponse { 
    uint32_t ipAddress;
} FLAME_DiscoveryResponse;

typedef struct _FLAME_ReviewPacket { 
    float actualAxis1;
    float actualAxis2;
    float actualAxis3;
    float actualAxis4;
    bool odrive0Axis0Error;
    bool odrive0Axis1Error;
    bool odrive0Error;
    bool odrv0ClearErrors;
    bool odrive1Axis0Error;
    bool odrive1Axis1Error;
    bool odrive1Error;
    bool odrv1ClearErrors;
    bool safetyMode;
    uint32_t badPackets;
    uint32_t stackUsage;
} FLAME_ReviewPacket;

typedef struct _FLAME_Wrapper { 
    pb_callback_t protocolVersion;
    bool has_discoveryPacket;
    FLAME_DiscoveryPacket discoveryPacket;
    bool has_discoveryResponse;
    FLAME_DiscoveryResponse discoveryResponse;
    bool has_controlPacket;
    FLAME_ControlPacket controlPacket;
    bool has_reviewPacket;
    FLAME_ReviewPacket reviewPacket;
} FLAME_Wrapper;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define FLAME_DiscoveryPacket_init_default       {0}
#define FLAME_DiscoveryResponse_init_default     {0}
#define FLAME_ControlPacket_init_default         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FLAME_ReviewPacket_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FLAME_Wrapper_init_default               {{{NULL}, NULL}, false, FLAME_DiscoveryPacket_init_default, false, FLAME_DiscoveryResponse_init_default, false, FLAME_ControlPacket_init_default, false, FLAME_ReviewPacket_init_default}
#define FLAME_DiscoveryPacket_init_zero          {0}
#define FLAME_DiscoveryResponse_init_zero        {0}
#define FLAME_ControlPacket_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FLAME_ReviewPacket_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define FLAME_Wrapper_init_zero                  {{{NULL}, NULL}, false, FLAME_DiscoveryPacket_init_zero, false, FLAME_DiscoveryResponse_init_zero, false, FLAME_ControlPacket_init_zero, false, FLAME_ReviewPacket_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define FLAME_ControlPacket_desiredAxis1_tag     1
#define FLAME_ControlPacket_desiredAxis2_tag     2
#define FLAME_ControlPacket_desiredAxis3_tag     3
#define FLAME_ControlPacket_desiredAxis4_tag     4
#define FLAME_ControlPacket_odrive0Axis0Error_tag 5
#define FLAME_ControlPacket_odrive0Axis1Error_tag 6
#define FLAME_ControlPacket_odrive0Error_tag     7
#define FLAME_ControlPacket_odrv0ClearErrors_tag 8
#define FLAME_ControlPacket_odrive1Axis0Error_tag 9
#define FLAME_ControlPacket_odrive1Axis1Error_tag 10
#define FLAME_ControlPacket_odrive1Error_tag     11
#define FLAME_ControlPacket_odrv1ClearErrors_tag 12
#define FLAME_ControlPacket_clearSafetyMode_tag  13
#define FLAME_DiscoveryResponse_ipAddress_tag    1
#define FLAME_ReviewPacket_actualAxis1_tag       1
#define FLAME_ReviewPacket_actualAxis2_tag       2
#define FLAME_ReviewPacket_actualAxis3_tag       3
#define FLAME_ReviewPacket_actualAxis4_tag       4
#define FLAME_ReviewPacket_odrive0Axis0Error_tag 5
#define FLAME_ReviewPacket_odrive0Axis1Error_tag 6
#define FLAME_ReviewPacket_odrive0Error_tag      7
#define FLAME_ReviewPacket_odrv0ClearErrors_tag  8
#define FLAME_ReviewPacket_odrive1Axis0Error_tag 9
#define FLAME_ReviewPacket_odrive1Axis1Error_tag 10
#define FLAME_ReviewPacket_odrive1Error_tag      11
#define FLAME_ReviewPacket_odrv1ClearErrors_tag  12
#define FLAME_ReviewPacket_safetyMode_tag        13
#define FLAME_ReviewPacket_badPackets_tag        14
#define FLAME_ReviewPacket_stackUsage_tag        15
#define FLAME_Wrapper_protocolVersion_tag        1
#define FLAME_Wrapper_discoveryPacket_tag        2
#define FLAME_Wrapper_discoveryResponse_tag      3
#define FLAME_Wrapper_controlPacket_tag          4
#define FLAME_Wrapper_reviewPacket_tag           5

/* Struct field encoding specification for nanopb */
#define FLAME_DiscoveryPacket_FIELDLIST(X, a) \

#define FLAME_DiscoveryPacket_CALLBACK NULL
#define FLAME_DiscoveryPacket_DEFAULT NULL

#define FLAME_DiscoveryResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ipAddress,         1)
#define FLAME_DiscoveryResponse_CALLBACK NULL
#define FLAME_DiscoveryResponse_DEFAULT NULL

#define FLAME_ControlPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    desiredAxis1,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    desiredAxis2,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    desiredAxis3,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    desiredAxis4,      4) \
X(a, STATIC,   SINGULAR, BOOL,     odrive0Axis0Error,   5) \
X(a, STATIC,   SINGULAR, BOOL,     odrive0Axis1Error,   6) \
X(a, STATIC,   SINGULAR, BOOL,     odrive0Error,      7) \
X(a, STATIC,   SINGULAR, BOOL,     odrv0ClearErrors,   8) \
X(a, STATIC,   SINGULAR, BOOL,     odrive1Axis0Error,   9) \
X(a, STATIC,   SINGULAR, BOOL,     odrive1Axis1Error,  10) \
X(a, STATIC,   SINGULAR, BOOL,     odrive1Error,     11) \
X(a, STATIC,   SINGULAR, BOOL,     odrv1ClearErrors,  12) \
X(a, STATIC,   SINGULAR, BOOL,     clearSafetyMode,  13)
#define FLAME_ControlPacket_CALLBACK NULL
#define FLAME_ControlPacket_DEFAULT NULL

#define FLAME_ReviewPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    actualAxis1,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    actualAxis2,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    actualAxis3,       3) \
X(a, STATIC,   SINGULAR, FLOAT,    actualAxis4,       4) \
X(a, STATIC,   SINGULAR, BOOL,     odrive0Axis0Error,   5) \
X(a, STATIC,   SINGULAR, BOOL,     odrive0Axis1Error,   6) \
X(a, STATIC,   SINGULAR, BOOL,     odrive0Error,      7) \
X(a, STATIC,   SINGULAR, BOOL,     odrv0ClearErrors,   8) \
X(a, STATIC,   SINGULAR, BOOL,     odrive1Axis0Error,   9) \
X(a, STATIC,   SINGULAR, BOOL,     odrive1Axis1Error,  10) \
X(a, STATIC,   SINGULAR, BOOL,     odrive1Error,     11) \
X(a, STATIC,   SINGULAR, BOOL,     odrv1ClearErrors,  12) \
X(a, STATIC,   SINGULAR, BOOL,     safetyMode,       13) \
X(a, STATIC,   SINGULAR, UINT32,   badPackets,       14) \
X(a, STATIC,   SINGULAR, UINT32,   stackUsage,       15)
#define FLAME_ReviewPacket_CALLBACK NULL
#define FLAME_ReviewPacket_DEFAULT NULL

#define FLAME_Wrapper_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   protocolVersion,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  discoveryPacket,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  discoveryResponse,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  controlPacket,     4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  reviewPacket,      5)
#define FLAME_Wrapper_CALLBACK pb_default_field_callback
#define FLAME_Wrapper_DEFAULT NULL
#define FLAME_Wrapper_discoveryPacket_MSGTYPE FLAME_DiscoveryPacket
#define FLAME_Wrapper_discoveryResponse_MSGTYPE FLAME_DiscoveryResponse
#define FLAME_Wrapper_controlPacket_MSGTYPE FLAME_ControlPacket
#define FLAME_Wrapper_reviewPacket_MSGTYPE FLAME_ReviewPacket

extern const pb_msgdesc_t FLAME_DiscoveryPacket_msg;
extern const pb_msgdesc_t FLAME_DiscoveryResponse_msg;
extern const pb_msgdesc_t FLAME_ControlPacket_msg;
extern const pb_msgdesc_t FLAME_ReviewPacket_msg;
extern const pb_msgdesc_t FLAME_Wrapper_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FLAME_DiscoveryPacket_fields &FLAME_DiscoveryPacket_msg
#define FLAME_DiscoveryResponse_fields &FLAME_DiscoveryResponse_msg
#define FLAME_ControlPacket_fields &FLAME_ControlPacket_msg
#define FLAME_ReviewPacket_fields &FLAME_ReviewPacket_msg
#define FLAME_Wrapper_fields &FLAME_Wrapper_msg

/* Maximum encoded size of messages (where known) */
/* FLAME_Wrapper_size depends on runtime parameters */
#define FLAME_ControlPacket_size                 38
#define FLAME_DiscoveryPacket_size               0
#define FLAME_DiscoveryResponse_size             6
#define FLAME_ReviewPacket_size                  50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
