/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "FLAME.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FLAME_DiscoveryPacket, FLAME_DiscoveryPacket, AUTO)


PB_BIND(FLAME_DiscoveryResponse, FLAME_DiscoveryResponse, AUTO)


PB_BIND(FLAME_ControlPacket, FLAME_ControlPacket, AUTO)


PB_BIND(FLAME_ReviewPacket, FLAME_ReviewPacket, AUTO)


PB_BIND(FLAME_Wrapper, FLAME_Wrapper, AUTO)



